filetype plugin indent on | syntax enable

set autoindent
set background=dark
set backspace=indent,eol,start
set belloff=all
set completeopt=menuone,noinsert,noselect
set directory=${HOME}/.cache/vim/swap//
set expandtab
set ignorecase
set incsearch
set laststatus=2
set list
set listchars=tab:^_,trail:-
set shiftwidth=0
set softtabstop=-1
set tabstop=2
set viminfofile=${HOME}/.cache/vim/viminfo
set virtualedit=block
set wildignorecase
set wildmenu

if has('termguicolors') && $COLORTERM ==# 'truecolor'
  let &t_8f = "\<Esc>[38:2:%lu:%lu:%lum"
  let &t_8b = "\<Esc>[48:2:%lu:%lu:%lum"
  set termguicolors
endif

let &t_SI .= "\e[6 q"
let &t_EI .= "\e[2 q"
let &t_SR .= "\e[4 q"

cnoremap <C-n> <Down>
cnoremap <C-p> <Up>

nmap s <Nop>
xmap s <Nop>

let g:loaded_2html_plugin = 1
let g:loaded_fzf = 1
let g:loaded_getscript = 1
let g:loaded_getscriptPlugin = 1
let g:loaded_gzip = 1
let g:loaded_logiPat = 1
let g:loaded_netrw = 1
let g:loaded_netrwFileHandlers = 1
let g:loaded_netrwPlugin = 1
let g:loaded_netrwSettings = 1
let g:loaded_rrhelper = 1
let g:loaded_tar = 1
let g:loaded_tarPlugin = 1
let g:loaded_vimball = 1
let g:loaded_vimballPlugin = 1
let g:loaded_zip = 1
let g:loaded_zipPlugin = 1

" python
let g:python_highlight_all = 1

" ruby
let g:ruby_indent_access_modifier_style = 'indent'
let g:ruby_indent_block_style = 'do'

" package manager
source <sfile>:h/minpac.vim

" ambicmd
cnoremap <expr> <Space> ambicmd#expand("\<Space>")
cnoremap <expr> <CR>    ambicmd#expand("\<CR>")

" gruvbox
let g:gruvbox_filetype_hi_groups = 1
let g:gruvbox_italics = 0
let g:gruvbox_italicize_strings = 0
let g:gruvbox_plugin_hi_groups = 1

colorscheme gruvbox8

" lightline
let g:lightline = {
      \ 'colorscheme': 'gruvbox8',
      \ }

" molder
nnoremap <silent> <Leader>f :<C-u>e %:p:h<CR>
nnoremap <silent> <Leader>F :<C-u>e .<CR>
