include_role 'base'

include_cookbook 'bat'
include_cookbook 'fzf'
include_cookbook 'ghq'
include_cookbook 'git'
include_cookbook 'gpg'
include_cookbook 'ripgrep'
include_cookbook 'tig'
include_cookbook 'tmux'
include_cookbook 'vim'
include_cookbook 'zsh'

include_cookbook 'asdf'
include_cookbook 'ruby'
